linetools/spectra/setup_package.py
Adds a setup_package.py file to spectra/, which is needed to install the test data in linetools/spectra/tests/files.  This allows testing with 'python setup.py test'.
=> Add setup_package.py to allow 'python setup.py test' to work

MANIFEST.in, setup.py
`python setup.py install` was failing due to peculiarities with setup.py pattern matching the 'linetools/data/lines' directory. This is a fix.
=> Change to fix build failure

linetools/spectra/io.py, linetools/spectra/tests/test_read_fits_spec.py
This fixes a bug (I think - please check carefully) in `setwave`, adds a warning if we guess the wavelengths are log, and adds a new test.  It also removes the assumption that `CRVAL1` and `CDELT1` are 1 if they aren't in the header, which seems a bad idea to me.
=> Fix bug in setwave, add warning, add tests

linetools/spectra/io.py, linetools/spectra/tests/test_read_fits_spec.py
Add a new function to refactor away duplicate code. This is similar to `get_cdelt()` in barak.spec.
=> Add get_cdelt_dcflag function to simplify reading fits spectra

linetools/analysis/interactive_plot.py, linetools/spectra/io.py, linetools/spectra/xspectrum1d.py
This adds basic classes to allow adding commands for interactive plotting.  XSpectrum1D.plot is tweaked enable XIDL-style keypress navigation, which I much prefer to the standard matplotlib navigation tools.
I plan to extend this with an interactive continuum fitting class soon.
Any comments welcome!
=> Add basic interactive plotting

linetools/spectra/io.py, linetools/spectra/tests/test_xspectrum_utils.py
This allows reading of spectra without an error array. It includes a test.
=> Allow reading of spectra without an error array

linetools/spectra/xspectrum1d.py
This adds a `matplotlib.pyplot.show()` command to XSpectrum1D.plot so that the plot will always appear automatically, even when running from a script. This can be disabled with a new show keyword.
=> Add plt.show to XSpectrum1D.plot

.travis.yml, linetools/__init__.py, linetools/analysis/__init__.py, linetools/analysis/continuum.py, linetools/lists/__init__.py, linetools/lists/linelist.py, linetools/lists/parse.py, linetools/spectra/__init__.py, linetools/spectra/io.py, linetools/spectra/lsf.py, linetools/spectra/tests/test_lsf_init.py, linetools/spectra/tests/test_lsf_use.py, linetools/spectra/tests/test_read_fits_spec.py, linetools/spectra/tests/test_xspec_init.py, linetools/spectra/tests/test_xspectrum_utils.py, linetools/spectra/xspectrum1d.py, linetools/spectralline.py, linetools/tests/test_absline_anly.py, linetools/tests/test_init_absline.py
We need to be Python 3 compatible if we want to be taken seriously by the astropy crowd :)
Therefore, this PR makes the changes necessary for linetools to work with Python 3.  All the tests pass in Python 3.4, and hopefully (!) Travis will now run the test suite using that python version, in addition to Python 2.7.
Note that there may still be python 3-related incompatibilities that aren't shown up by our tests.
=> Make compatible with Python 3

linetools/lists/linelist.py
Reading linelists can be slow if you need to do it several times in a single python session. This minimises re-reading lists (like 'Strong', 'ISM', etc.) by storing them in a dictionary.
=> Linelist cache

docs/api.rst, docs/conf.py, docs/index.rst, docs/install.rst, linetools/spectralline.py
This updates `spectralline.py` so that Sphinx will parse the docstrings correctly (according to the rules given at http://docs.astropy.org/en/stable/development/docrules.html). I suggest we use `spectralline.py` as a template for future docstrings.
You can see the result here: https://dl.dropboxusercontent.com/u/7970232/linetools_docs/index.html
(go to linetools API -> SpectralLine, for example).
I've also updated the installation docs with instructions on how to build the docs.
=> Update spectralline.py so Sphinx can parse docstrings

linetools/spectra/tests/test_xspectrum_utils.py, linetools/spectra/xspectrum1d.py
Add the XSpectrum1D copy method, which I accidentally removed in the last PR. Also fixes a bug in the original version.
=> Add copy method (again)

linetools/isgm/abssystem.py, linetools/isgm/lls.py, linetools/isgm/tests/test_use_abssys.py
A new method or two
and a test
=>  LLS: Some edits for the LLS GUI

docs/scripts.rst, linetools/analysis/interactive_plot.py, linetools/scripts/linet_absline.py, linetools/scripts/lt_plot.py, setup.py
This adds a simple command-line script to plot one or more spectrum files. Currently it's not much more than a wrapper around `XSpectrum1D.plot`.
=> Add a quick plot script (an "xspec lite")

.travis.yml, docs/abscomp.rst, docs/absline.rst, docs/abssys.rst, docs/builddocs.sh, docs/conf.py, docs/index.rst, docs/install.rst, docs/scripts.rst, docs/solar.rst, docs/xspectrum1d.rst, linetools/spectra/convolve.py, linetools/spectra/tests/test_xspectrum_utils.py
This has a few changes (sorry):
* Remove the convolve_window function, which I don't think is used anywhere
* Remove the rest highlighting commands at the top of the doc files, because they prevent code highlighting in examples
* Normalise the Gaussian smoothing kernel in convolve_psf. Without this,  a spectrum's normalisation changes a lot when you smooth it with a narrow psfs.
=> Remove convolve_window, doc changes, normalise gaussian smoothing kernel

linetools/spectra/io.py, linetools/spectra/xspectrum1d.py
only useful for binary tables, e.g. PYPIT
=> xspectrum1d: Exten keyword for multi-extension FITS

linetools/spectra/io.py
This was making the readthedocs build fail.
=> Remove Pyqt import

linetools/spectra/lsf.py
because it's not used, and makes us incompatible with scipy versions < 0.14 (apparently used by readthedocs...)
=> Remove Akima1DInterpolator import

linetools/analysis/interactive_plot.py, linetools/spectra/xspectrum1d.py, linetools/utils.py
This fixes a bug in the continuum fitting code: it would fail to save continuum points if the spectrum's flux is type numpy.float32, instead of the numpy float64 (which is the native python type, I think).
It also adds a (slightly) more informative error message if no continuum spline points are found, and cleans up the loadjson and savejson functions.
=> Fix bug in continuum fitting

docs/AbsComponent_ColumnDensities.rst, docs/AbsComponent_examples.rst, docs/AbsLine_examples.rst, docs/AbsSystem_examples.rst, docs/SolarAbund.rst, docs/examples/AbsSystem_examples.ipynb, docs/nb_to_rst.src, docs/xspecgui.rst
This alters the notebook conversion script so that at the beginning of each generated .rst file there's a link to the original notebook file.
=> Add a link to the original examples notebooks in the sphinx rst versions

linetools/spectra/tests/test_xspectrum_utils.py, linetools/spectra/xspectrum1d.py
- I've added a method for un-normalizing a spectrum.
- Added boolean attribute ``self.normed`` which helps in avoiding the possibility of `normalize` a normalized spectrum (i.e. divide by the continuum again).
=> Xspectrum1d: normalize/unnormalize

docs/xspectrum1d.rst, linetools/guis/spec_widgets.py, linetools/guis/xspecgui.py, linetools/spectra/io.py, linetools/spectra/tests/test_xspec_init.py, linetools/spectra/xspectrum1d.py
I found spectra.io.readspec very confusing. This refactors it so it's more clear what is going on (to me anyway, and hopefully other people who aren't @profxj...). 
Note that I also removed the ability to specify flux and wavelength tags, because this makes the code simpler, and because the list of tags in the docs was getting out of sync with the list used in the code.  It now just prints the list of tags if one of them can't be found.
It also makes ExamineSpecWidget plot the continuum by default.
=> Refactor readspec

linetools/guis/spec_widgets.py
This makes the '?' key open a browser pointing to the xspecgui notebook instructions, and fixes an issue with the norm keyword.
=> Add ? help key and normalisation fix to ExamineSpecWidget

linetools/analysis/voigt.py, linetools/spectra/xspectrum1d.py
XSpectrum1D: make sure sigma is well defined for gaussian smoothing.
=> XSpectrum1D: make sure sigma is well defined for gaussian smoothing.

linetools/guis/line_widgets.py, linetools/guis/spec_widgets.py, linetools/guis/xspecgui.py
This removes a reference to Spectrum1D, and fixes continuum plotting in ExamineSpecWidget.  It also multiplies the flux model by the continuum when using the 'D' and 'R' options to plot DLA/SLLS profiles.
=> Xspec changes

linetools/spectra/tests/test_xspectrum_utils.py, linetools/spectra/xspectrum1d.py
This allows assigning arrays directly to the wavelength, flux, sig and co attributes. e.g.
```python
wa = np.arange(10)
fl = np.ones_like(wa)
sp = XSpectrum1d.from_tuple((wa, fl))
wave = np.arange(1, len(sp.wavelength) + 1)
sp.wavelength = wave
```
Units are updated for the wavelength or flux (if the assigned array is a Quantity), and ignored for sig and co.
Tests are included.
=> Allow assigning values to XSpectrum1D attributes

linetools/guis/xspecgui.py, linetools/scripts/lt_plot.py, linetools/spectra/xspectrum1d.py
I find scientific notation annoying in the wavelength axis...
=> Scripts: avoid scientific notation when possible for axes tick labels.

linetools/isgm/abssystem.py, linetools/isgm/tests/test_init_abssys.py
Puts a 'hook' into AbsSystem specific to DLASystem
which comes from pyigm.
Doesn't generate a dependence of pyigm for linetools,
but is not an elegant approach.  Might be a first
step towards pushing AbsSystem into pyigm..
=> AbsSystem/DLASystem: from_components

CHANGES.rst, linetools/spectra/tests/test_xspec_init.py, linetools/spectra/xspectrum1d.py
Fixes a bug in `from_tuple` if the input wavelength array object has a `unit` attribute but no `value` attribute (which is possible for astropy table columns.)
=> Allow an astropy table column for wavelengths in from_tuple

linetools/guis/spec_widgets.py
edits to ExamineSpec to deal with continuum changes
No new tests or docs, but used on real spectra
=> ExamineSpec

linetools/isgm/abscomponent.py, linetools/isgm/abssystem.py, linetools/isgm/utils.py, linetools/lists/linelist.py, linetools/spectralline.py, linetools/tests/test_absline_anly.py
A number of modifications to speed-up linetools.
Mainly for cases where a large number of absorption systems
and/or components are being loaded from dict's.
Most changes are optional and not the default.
Key exception is a memoization of LineList.
Tested on COS-Halos in pyigm extensively (lead to a 10x speed-up).
=> Linetools Speed up

linetools/isgm/abscomponent.py, linetools/spectra/xspectrum1d.py
Also allow passing arbitrary keyword arguments to XSpectrum1D.box_smooth(), to be passed on to astropy.convolution.convolve.
=> Remove a specutils import

.travis.yml
There's a problem with travis testing of numpy version 1.9, so this removes that test. I don't think we need to worry about supporting 1.9 anymore anyway, later stable versions are now in anaconda.
=> Remove numpy 1.9 from travis testing

docs/install.rst, linetools/isgm/abssystem.py
Warnings
pvlim in stack_plot()
Failing things in Python 3.5
Anyone know why??
=> AbsSystem edits

linetools/isgm/tests/test_use_abscomp.py, linetools/isgm/utils.py
- group_coincident_components() implemented
- with test
This function will be useful for VP fitting a full spectrum, where components that are isolated are easy to identify, and so those that are coincident in wobs with others. It may be a bit of a pain to review it...
=> Abscomp utils: group_coincident_components()

linetools/spectra/xspectrum1d.py
box_smooth failed when no error array was given and "preserve" was set to True.
These lines fixed that issue by checking first if there is an error array, and setting the new error array (new_sig) to None if self.sig_is_set == False
=> Fixing box_smooth when no error array is given

docs/xspectrum1d.rst, linetools/spectra/tests/test_xspec_io.py, linetools/spectra/tests/test_xspec_utils.py, linetools/spectra/utils.py, linetools/spectra/xspectrum1d.py
Rebin all the spectra in an XSpectrum1D object.
Default is the selected on.
Also pushed the rebin method to spectra.utils
And deprecated from_list as it was duplicated by collate()
docs and tests updated
=> Rebin all of the spectra in XSpectrum1D

linetools/spectra/io.py, linetools/spectra/tests/test_xspec_io.py, linetools/spectra/utils.py
Allows for using dict objects instead of Header objects
in XSpectrum1D meta.
Should probably add a test..
=> dict in meta for XSpectrum1D

docs/install.rst
Updates install notes for PyQt with conda which
now requires explicit specification of the version
=> pyqt4 installation notes

linetools/isgm/abssystem.py, linetools/isgm/tests/files/generic_abssys.json, linetools/isgm/tests/test_init_abssys.py, linetools/isgm/tests/utils.py, linetools/isgm/utils.py
As titled.
Deals with the arbitrary ordering of dict keys.  This could
create unusual (and at the least unpredictable) behavior
when reading comopnents from disk.
Added a new test file and test.
=> Order the components by z after reading from_dict

linetools/isgm/abscomponent.py, linetools/isgm/tests/test_use_abscomp.py, linetools/isgm/utils.py, linetools/lists/parse.py
A patch for AbsComponents to work (at a basic level without checks) with H2 lines. This PR is only  meant to make pyigm's IGMguesses to be able to handle H2 molecules. A more fundamental solution is beyond the scope of this PR.
=> AbsComponent H2

docs/xspec_multi.rst, docs/xspectrum1d.rst, linetools/spectra/tests/test_xspec_utils.py, linetools/spectra/utils.py, linetools/utils.py
Updates collate() method.  Allows for multiple spectra
in each input XSpectrum1D object.
Updates tests and docs
=> Collate in XSpectrum1D

docs/absline.rst, linetools/analysis/absline.py, linetools/analysis/tests/test_absline.py, linetools/spectralline.py, linetools/tests/test_absline_anly.py
N_from_Wr() and N_from_Wr_transition() added to linetools.analysis.absline; these are useful for getting upper limits on N from measured Wr upper limits. Assume tau0<<1 where the relation between N and Wr is independent on Doppler parameter and gamma.
=> laa: added N_from_Wr() and N_from_Wr_transition() with tests.

docs/install.rst
As titled.
The pip wheel we have in PyPi is woefully out of date.
Until we figure out how to update (may require Neil) 
the install should be via git clone.
=> Scrub pip install for now

linetools/tests/test_utils.py, linetools/utils.py
As titled.
Solely for the radec_to_coord() method.
No new docs.
=> Enable list for RA/DEC input

linetools/guis/line_widgets.py, linetools/guis/spec_widgets.py, linetools/lists/linelist.py, linetools/lists/mk_sets.py, linetools/lists/parse.py, linetools/lists/tests/test_init_linelist.py, linetools/lists/tests/test_use_linelist.py, linetools/spectralline.py
Despite my original fascination with QTable's, I've come
to consider them a greater pain than good.
This PR removes the use of QTable's in linelists in linetools.
tests updated
no doc changes aside from those in the modules
It is possible a Notebook or two will break, but I doubt it.
=> Refactor linelists from QTable -> Table

linetools/guis/line_widgets.py
I found that I needed to explicitly initialize `self.line` in `SelectLineWidget` for not breaking IGMGuesses using such widget (see also PR#108 in pyigm).
=> SelectLineWidget. Init self.line attribute as str.

linetools/spectra/lsf.py
As stated. This will prevent an error from future.
=> lsf: impose n_half to be integer in lsf.py

linetools/guis/spec_widgets.py, linetools/guis/xspecgui.py, linetools/scripts/lt_xabssys.py, linetools/scripts/lt_xspec.py, linetools/spectra/io.py, linetools/spectra/xspectrum1d.py
As titled.
Also adds functionality to dynaimcally set gui size
based on number of pixels in the monitor.
No new docs or tests.
=> Add widget to lt_xspec for selecting between multiple input spectra

linetools/analysis/interactive_plot.py, linetools/guis/spec_widgets.py
A bit aggressive, but a nice way to stop PyQt crashing
on a bad key-stroke entry.
I don't think there is a downside.  We could include key
clicks and also add to pyigm (e.g. igmguesses).
=> Catch all for GUI key stroke errors

linetools/scripts/lt_radec.py
As advertised.
Small changes for a somewhat cleaner look.
=> Cleaner look for lt_radec

linetools/analysis/tests/test_zlimits.py, linetools/analysis/utils.py, linetools/analysis/zlimits.py, linetools/isgm/abscomponent.py, linetools/isgm/tests/test_init_abssys.py, linetools/isgm/tests/test_use_abscomp.py, linetools/isgm/tests/utils.py, linetools/isgm/utils.py, linetools/spectralline.py
There are two threads to this PR:
- Refactor from LineLimits to zLimits
- Add a unique_components() method
The first allows for limits without reference to wrest.
That becomes optional, so previous functionality is maintained.
The second is a method useful for querying lists of components.
I also removed GaussianAbsorption1D as that is deprecated in astropy.
Includes a new test, but no new docs.
=> Unique components

linetools/isgm/abscomponent.py, linetools/isgm/abssystem.py, linetools/isgm/tests/test_init_abscomp.py, linetools/isgm/tests/test_use_abscomp.py, linetools/isgm/utils.py
Edits mainly to speed up reading JSON files.
Also turned off 'stars' as a required parameter when
generating a fine-structure component.  Defaults
to a single star if not provided.
Failing one Travis test which is not related to linetools.
=> A few AbsComponent edits

.travis.yml, linetools/analysis/tests/test_voigt.py, linetools/analysis/voigt.py
=> Voigt model

docs/linelist.rst, linetools/lists/linelist.py, linetools/lists/tests/test_use_linelist.py
Make LineList.all_transitions and LineList.strongest_transitions accept Zion tuple, e.g., (8,6)
=> Transition lookup by Zion tuple

linetools/guis/spec_widgets.py, linetools/spectra/xspectrum1d.py
=> Small fix for Gaussian in spec_widgets

linetools/analysis/plots.py, linetools/analysis/tests/test_plots.py
Minor addition for plots.stack_plot to accept zref argument instead of using redshift for each AbsLine.  Useful for stack plots relative to a systemic redshifts.
=> Add reference redshift option for stack plots

linetools/isgm/abscomponent.py, linetools/isgm/abssystem.py, linetools/isgm/utils.py, linetools/spectralline.py
Extends the AbsComponent object so that b values and velocity centroids are attribs.  Also, method to shift component velocities to systemic value.  Includes above attribs in component table.
=> AbsSystem and AbsComponent attributes

linetools/scripts/lt_get_COS_LP.py, linetools/scripts/tests/test_scripts.py
Script to get HST/COS LP from date. I found this convenient to have as a script.
=> added script to get HST/COS LP from date + test

linetools/isgm/abscomponent.py, linetools/isgm/abssystem.py
As titled.
Several IGMSurveys in pyigm were
crashing because of the coord speed-up.
No new tests or docs.
=> Two small, useful edits related to Components

linetools/abund/elements.py
The III->IV ionization energy was incorrect due to a duplicated entry in the ionenergy tuple for O.
=> Fix oxygen

linetools/isgm/abscomponent.py, linetools/isgm/tests/test_use_abscomp.py
The from_dict_to_table() method had apparently been moved to linetools.lists.utils, but this had not been refactored in AbsComponent.add_abslines_from_linelist()
=> Abscomponent bug fix

linetools/isgm/abssystem.py, linetools/isgm/emsystem.py
As stated, trivial changes to allow Figure object passthrough for abssystem and emsystem when using return_fig option
=> Return Figure object for abssystem and emsystem

linetools/guis/spec_widgets.py
As stated.
(Regarding remembering flux limits too, I think is better for xspec to guess the y-limits depending on each data than fixing it.)
=> Remember wvlim in lt_xspec

.travis.yml, docs/install.rst, linetools/conftest.py, linetools/spectra/io.py
As titled.
A few bits and pieces here.
Only test fail is astropy development.  That will
eventually get us but I'm ok with what we have for now.
=> Add continuum tag for spec I/O, update Install and travis

linetools/conftest.py
Hi there :wave:, it looks like you likely used the astropy package template in the past for your package and we noticed that your conftest.py file is now out of date and imports pytest plugins from astropy:
```python
from astropy.tests.pytest_plugins import *
```
This astropy sub-package has been removed, so your tests will likely be failing now that astropy v3.2 has been released. This PR therefore fixes this import by checking the astropy version and adjusting the import as needed.
We also wanted to let you know that we have made new releases of the astropy package-template. If your package still needs to support Python 2, you can find the latest [Python 2-compatible cookiecutter template here](https://github.com/astropy/package-template/tree/cookiecutter-2.x) or if you prefer you can …
=> Fix compatibility of conftest.py with Astropy 3.2

docs/nb/Integrating_Specutils.ipynb, linetools/analysis/plots.py, linetools/analysis/tests/test_plots.py, linetools/guis/spec_widgets.py, linetools/spectra/io.py, linetools/spectralline.py
As titled.
No new tests or docs
=> Small edits for PypeIt compatability

linetools/spectra/io.py
FUSE NVO files in the MAST archive adopt the units of  'ANGSTROMS' (all upper case), which doesn't get captured in the present list of spectra/io.py. Adding this to line 305 fixes the issue.
=> Add 'ANGSTROMS' unit to account for FUSE data in spectra/io.py.

linetools/analysis/plots.py, setup.py
This should make it so that, if a linetools sdist is made inside a linetools git repo, the correct version will go into version.py
Then, when installing from that sdist not in a linetools git repo, the correct version is pulled from version.py
This should make it so that the linetools conda-forge package will provide the correct value for linetools.__version__
I'll test the creation of and installation from sdists and report back results.
=> Update dev version handling

linetools/analysis/plots.py
matplotlib >3.0.3 produces error when trying to use 'step-mid' with the linestyle attribute as this was deprecated behavior.  
Also adding another way to make a stackplot from spec_file
=> fussing with stack plot

.travis.yml, setup.py
Followup to #520 , this time with verification that the resulting sdists, when installed generate the correct `linetools.__version__` field
=> Actually fix dev version handling

linetools/isgm/utils.py
`group_coincident_components()` could miss potential blends if the upper wvlim of line `i` is redder than the upper wvlim of line `i+1`.
```
i    ----------------
i+1         ----
i+2               -------------
```
=> fixing misssed component blends

linetools/spectra/io.py
An update to `astropy` appears to have it no longer
slurp in extra long CONTINUE's of strings.  This
lends to a crash when trying to read them in.
This PR offers a hack/fix as a temporary solution.
=> Avoid crash with overly long METADATA card

linetools/abund/solar.py, linetools/analysis/absline.py, linetools/analysis/tests/test_continuum.py, linetools/analysis/tests/test_continuumfnd.py, linetools/isgm/tests/test_use_abscomp.py, linetools/lists/mk_sets.py, linetools/lists/parse.py, linetools/lists/tests/test_init_linelist.py, linetools/spectra/lsf.py
Replaced some more uses of imp with to importlib. Running tests with pytest doesn't flag anything up, though that was just with astropy 6.0.0 and numpy 1.26.3
=> imp -> importlib

linetools/isgm/tests/test_io.py, linetools/isgm/tests/utils.py, linetools/lists/linelist.py, linetools/lists/parse.py, linetools/tests/test_utils.py
As titled, `pkg_resources` has been deprecated for some time and finally broken in Python 3.12. This PR also rids the `frb` repository of some errors related to the `linetools` dependency.
=> Pkg resources
