- docs/LineList_examples.ipynb
- linetools/spectra/io.py
- linetools/spectra/tests/test_read_fits_spec.py
- linetools/spectra/utils.py
Added functionality to io.py and utils.py to enable reading
FITS files.  Adds functionality that I was hoping to integrate
within specutils.
> xspectrum1d I/O

- linetools/spectra/io.py
1 minor change
and 1 new keyword for get_table_column
> Spectral line

- linetools/lists/linelist.py
- linetools/lists/tests/test_use_linelist.py
LineList all_transition_names_from_line() added.
Simple test passed.
> Linelist: all_transition_names_from_line()

- linetools/spectra/io.py
- linetools/spectra/utils.py
Enable reading standard SDSS spectra .fit files (e.g. from DR7).
Put histogram as default in plotting
> reads SDSS; small edit to XSpectrum1D.plot

- linetools/spectra/io.py
> Enable parsing of GGG GMOS spectra

- linetools/spectra/io.py
- linetools/spectra/tests/test_read_fits_spec.py
Fix a change which was incorrectly added to PR #41 that breaks xastropy. Also add a test.
> Fix a regression from a previous PR, and add test

- linetools/lists/linelist.py
- linetools/lists/tests/test_use_linelist.py
strongest_transitions() and available_transitions() implemented in LineList.
> Linelist: strongest_transitions() and available_transitions() implemented

- linetools/spectra/io.py
Small edit for X-Shooter XQ-100 table format.
> Xspectrum1d

- linetools/spectra/convolve.py
Old versions of convolve_window() and convolve_psf() removed.
> Old versions of convolve_window() and convolve_psf() removed.

- .travis.yml
- docs/examples/Interactive_continuum_fitting_example.ipynb
- linetools/analysis/continuum.py
- linetools/analysis/interactive_plot.py
- linetools/analysis/tests/test_continuum.py
- linetools/spectra/xspectrum1d.py
This adds the ability to interactively fit a continuum to a spectrum, inspired by the fitcont code from Barak. There is an ipython notebook giving example usage.
I'm not sure how to add tests for interactive code like this - any suggestions are welcome.
> Interactive continuum fitting 

- linetools/lists/linelist.py
LineList: minor tweaks; basically strongest_transitions() and available_transitions() can now specify n_max (or n_max_tuple) as None, meaning retrieve everything.
> LineList: minor tweaks

- linetools/spectra/io.py
I should probably add a test for this one of these days..
Note: Coverage tests aren't working now due to an upgrade in
the Travis software.  Hopefully the astropy folks will put in a fix
that we can copy soon enough.
> edit to maintain table input to readspec

- linetools/lists/linelist.py
- linetools/spectra/tests/test_read_fits_spec.py
Add a test to avoid a future regression similar to #65. Also tweaks some docstrings to display well in command line ipython.
> Add a test for reading spectra from an astropy Table, plus some docstring improvements

- .travis.yml
- linetools/analysis/continuum.py
- linetools/spectra/io.py
- linetools/spectra/tests/test_read_fits_spec.py
- linetools/spectra/tests/test_xspec_init.py
- linetools/spectra/xspectrum1d.py
- linetools/spectralline.py
It also adds a workaround for this issue astropy/specutils#123.
> Add python 3.5, numpy 1.10 to travis testing

- docs/install.rst
A doc page on installation.  I haven't actually checked that following these instructions works...
> Installation docs

- docs/install.rst
Fixes some bugs in the first version.
> Install doc changes

- docs/api.rst
- linetools/abund/ions.py
- linetools/abund/roman.py
- linetools/abund/solar.py
- linetools/isgm/abscomponent.py
- linetools/utils.py
This makes `abund` and `utils`  compatible with Sphinx. automodapi doesn't parse elements.py for some reason, I'm skipping it for now. 
Once I finish the first pass through everything, I'll add a documentation build to the Travis tests.
> More docstring Sphinxification

- linetools/analysis/continuum.py
- linetools/analysis/interactive_plot.py
- linetools/analysis/tests/test_continuum.py
- linetools/spectra/tests/test_xspectrum_utils.py
- linetools/spectra/xspectrum1d.py
This adds a copy method to XSpectrum1D, and allows a continuum input to XSpectrum1D.from_tuple.
There are also a few doc tweaks and minor bugfixes (sorry to lump them together).
> Add a copy method to XSpectrum1D

- linetools/spectra/tests/test_xspectrum_utils.py
- linetools/spectra/xspectrum1d.py
also fix a bug with the __repr__ test and other small changes. I will merge when tests pass.
> Fix a bug in XSpectrum1D.__repr__

- docs/AbsComponent_examples.rst
- docs/AbsSurvey_examples.rst
- docs/AbsSystem_examples.rst
- docs/abssurvey.rst
- docs/examples/AbsSurvey_examples.ipynb
- docs/index.rst
- docs/nb_to_rst.src
- linetools/isgm/abssurvey.py
- linetools/isgm/tests/test_init_abssurvey.py
AbsSurvey class
Pretty bare bones but includes:
test
docs 
notebook
> AbsSurvey -- Beginnings

- linetools/spectra/io.py
- linetools/spectra/xspectrum1d.py
Neil's fix has at least one unintended consequence.
Please fast track this.
Thanks, X
> xspectrum1d: Another kludge for the numpy bug

- linetools/isgm/abscomponent.py
- linetools/isgm/tests/test_use_abscomp.py
Added self.name attribute to AbsComponent
Added self.comment attribute to AbsComponent
Added repr_vpfit() to AbsComponent
Other minor stuff
> Abs component

- linetools/isgm/abscomponent.py
- linetools/isgm/tests/test_use_abscomp.py
abscomponent: added repr_alis()
> abscomponent: added repr_alis()

- .travis.yml
- docs/abscomp.rst
- docs/abssys.rst
- docs/api.rst
- docs/builddocs.sh
- docs/conf.py
- docs/index.rst
- linetools/abund/ions.py
- linetools/lists/mk_sets.py
- linetools/spectra/xspectrum1d.py
Now down to just 10 Sphinx warnings (yay!).
> More doc changes

- linetools/analysis/voigt.py
- linetools/isgm/lls.py
I will merge them once tests pass.
> Minor changes to voigt.py and lls.py

- docs/install.rst
- linetools/abund/ions.py
- linetools/abund/roman.py
- linetools/isgm/abscomponent.py
- linetools/lists/linelist.py
- linetools/lists/parse.py
- linetools/lists/tests/test_use_linelist.py
This removes the old roman to integer code, and fixes a bunch of sphinx warnings.
> Remove duplicate roman numeral code, fix remaining (?) sphinx warnings

- docs/AbsLine_examples.rst
- docs/absline.rst
- docs/index.rst
- docs/nb_to_rst.src
- linetools/spectralline.py
Also some minor changes in spectralline.py
> First pass at AbsLine docs

- docs/SolarAbund.rst
- docs/absline.rst
- docs/api.rst
- docs/index.rst
- docs/nb_to_rst.src
- docs/solar.rst
- linetools/abund/elements.py
- linetools/abund/ions.py
- linetools/abund/solar.py
- setup.cfg
Also some other minor changes.
> Add docs for the SolarAbund class

- linetools/analysis/voigt.py
- linetools/spectra/io.py
> A few small edits in docs, mainly

- linetools/isgm/abssystem.py
- linetools/isgm/tests/test_init_abssys.py
> abssystem: RA/DEC as strings input

- linetools/isgm/abssystem.py
- linetools/isgm/tests/test_init_abssys.py
- linetools/utils.py
May push this out of AbsSystem before long
> AbsSystem: overloading radec yet more

- docs/rtd-pip-requirements
This is needed to build the documentation on https://readthedocs.org/
> Add read the docs requirements file

- linetools/tests/test_utils.py
- linetools/utils.py
Minor edits related to bulding CGM in pyigm
Added inline docs
Edited test
> CGM changes

- docs/linelist.rst
- linetools/lists/linelist.py
- linetools/lists/tests/test_init_linelist.py
- Added documentation in linelist.rst
- Solved an issue with subset sorting in linelist.py
> Docs: LineList

- linetools/analysis/plots.py
- linetools/isgm/abscomponent.py
Pushed stack_plot into its own module
> Refactored stack plot

- linetools/spectralline.py
Added an attribute to SpectralLine for kinematic analysis
> spectral_line: Kinematic attribute

- docs/abscomp.rst
- docs/abssys.rst
- linetools/isgm/abscomponent.py
- linetools/isgm/abssystem.py
- linetools/isgm/tests/test_use_abscomp.py
- linetools/isgm/tests/test_use_abssys.py
- linetools/isgm/utils.py
read and write methods using dict's for
AbsSystem and AbsComponent
docs
tests
> dicts: AbsSystem and AbsComponent

- linetools/isgm/abscomponent.py
- linetools/isgm/abssystem.py
- linetools/isgm/utils.py
- linetools/spectralline.py
A bit more related to read/write of AbsSystem, components, etc.
> AbsSystem:  More dict

- linetools/isgm/abssystem.py
> Minor pdb fix

- linetools/guis/simple_widgets.py
a few simple widgets (from xastropy)
no tests, no docs (aside from inline)
> Simple Widgets

- linetools/analysis/interactive_plot.py
- linetools/guis/spec_widgets.py
- linetools/guis/utils.py
- linetools/spectra/xspectrum1d.py
Synthesizes navigate
Fixes dir() method
no tests, no docs
> Navigate and dir()

- linetools/isgm/abscomponent.py
- linetools/spectra/xspectrum1d.py
- linetools/spectralline.py
Spectralline: tweaks to docstring and code.
> Spectralline: tweaks to docstring and code.

- linetools/analysis/absline.py
- linetools/isgm/abssystem.py
- linetools/isgm/tests/test_use_abscomp.py
- linetools/spectralline.py
- linetools/tests/test_absline_anly.py
Deals with a few issues
and tests
> AODM and other fixes

- linetools/analysis/interactive_plot.py
- linetools/guis/spec_widgets.py
- linetools/guis/xspecgui.py
- linetools/scripts/lt_xspec.py
This makes some changes to the xpsec gui to make the startup time faster. It 
- removes a redundant call to guis.utils.read_spec 
- shifts around some imports
- replaces try-except statements, because catching exceptions is slow.
My subjective impression is that these speed up startup by a bit.
> xspec gui enhancements

- linetools/guis/spec_widgets.py
Fixes display of y-position in spec_widget
Nothing else
> small GUI edit

- linetools/spectra/io.py
Added a few more tags for readspec
> Spectra IO

- linetools/abund/tests/test_elements.py
> elements: added some tests

- CHANGES.rst
- docs/api.rst
- docs/changelog.rst
- docs/index.rst
- docs/scripts.rst
- docs/xspectrum1d.rst
- linetools/spectra/xspectrum1d.py
> XSpectrum1D docs, other doc tweaks

- linetools/analysis/voigt.py
- linetools/guis/spec_widgets.py
> Fix for U/D keys in xspec gui

- docs/linelist.rst
- docs/xspectrum1d.rst
> docs: tweaks to docs.

- docs/linelist.rst
- linetools/guis/utils.py
- linetools/lists/linelist.py
- linetools/lists/tests/test_init_linelist.py
- linetools/lists/tests/test_use_linelist.py
LineList: Making subset_lines() to return a LineList object instead.
Initial commit; will use Travis to check up crashes from tests and will fix them one at a time.
>  LineList: Making subset_lines() to return a LineList object instead.

- docs/install.rst
- docs/linelist.rst
- docs/xspecgui.rst
removed pyaml as a dependency in install
changed pip call too
small edits to linelist.rst
> Docs edits

- docs/scripts.rst
- docs/xspecgui.rst
- linetools/guis/spec_widgets.py
- linetools/guis/utils.py
- linetools/scripts/lt_continuumfit.py
- linetools/scripts/lt_xspec.py
- linetools/spectra/io.py
- setup.py
new script
some docs
a few other edits
> Script for Continuum Fit

- linetools/spectra/xspectrum1d.py
Eventually, it would be nice to have the splice smart enough to realize which one is on the shorter/longer wavelength side...
> XSpectrum1D: Minor correction to docstring.

- README.md
The coveralls website is down, but once it's back up I'll work out how to add that badge too.
> Add astropy and travis build badges to the README

- linetools/guis/spec_widgets.py
> Small bug fix for spec_widget

- linetools/spectra/tests/test_xspectrum_utils.py
- linetools/spectra/xspectrum1d.py
xspectrum1d: rebin: re-interpolate continuum if `co_is_set` to the new wv array.
> xspectrum1d: rebin: rebins continuum if `co_is_set`.

- linetools/spectra/tests/test_xspectrum_utils.py
- linetools/spectra/xspectrum1d.py
I am finding it useful on occasion to generate a distinct 
spectrum object that is the normalized version.
Added a test too.
> Generate normalized spectrum

- linetools/spectra/io.py
> Xspec IO: Var fix

- linetools/guis/spec_widgets.py
- linetools/guis/utils.py
- linetools/guis/xspecgui.py
- linetools/scripts/lt_xspec.py
- linetools/spectra/io.py
- linetools/spectra/tests/test_read_fits_spec.py
This is a bit unwieldy, but I'm not sure if there is a better 
approach.  Please suggest one if you see it.
> Tag keywords for lt_xspec

- docs/abssys.rst
- linetools/isgm/abssystem.py
- linetools/isgm/tests/test_use_abssys.py
- linetools/isgm/utils.py
> AbsSystem: Fill _ionN method

- linetools/spectra/tests/test_xspectrum_utils.py
- linetools/spectra/xspectrum1d.py
> Bug fix for wvmin/max

- linetools/isgm/abscomponent.py
- linetools/isgm/tests/test_use_abscomp.py
Some small edits for synthesizing components with lines that
don't contribute to the column.
And a test modification
> Synth_comp

- linetools/analysis/interactive_plot.py
- linetools/guis/line_widgets.py
- linetools/guis/spec_widgets.py
- linetools/isgm/abssystem.py
- linetools/isgm/setup_package.py
- linetools/isgm/tests/files/HILya_abssys.json
- linetools/isgm/tests/test_init_abssys.py
- linetools/lists/linelist.py
- linetools/spectralline.py
Series of minor edits to:
a.  Refactor abs_type in AbsSystem
b.  Deal with some syntax/bugs when running in Python 3
c.  Some GUI edits
d.  Added a test to cover AbsSystem.from_dict and from_json
e.  Addresses 'crash' when running measure_EW or measure_AODM on a 'bad' spectrum
> Odds and Ends: AbsSys, Python3 

- docs/guis.rst
- docs/xabssysgui.rst
- linetools/guis/line_widgets.py
- linetools/guis/spec_widgets.py
- linetools/guis/tests/test_guis.py
- linetools/guis/xabssysgui.py
- linetools/guis/xspecgui.py
- linetools/scripts/lt_xabssys.py
- setup.py
Here is a new GUI that I would tend to use to 
examine and modify the lines of an AbsSystem.
It has some similar concepts to IGMGuesses but
is only 1 system at a time.
Have tested it on a DLA but there are no formal tests
with this PR.  
Have included some documentation and can be pushed to
include more.
> XAbsSysGui

- docs/examples/AbsLine_examples.ipynb
- docs/examples/AbsSystem_examples.ipynb
- docs/specline.rst
- linetools/analysis/absline.py
- linetools/guis/xabssysgui.py
- linetools/isgm/abscomponent.py
- linetools/isgm/abssystem.py
- linetools/isgm/tests/test_use_abssys.py
- linetools/isgm/utils.py
- linetools/line_utils.py
- linetools/spectralline.py
- linetools/tests/test_line_utils.py
A series of edits related to measuring abundances in 
an AbsSystem.
Tests, docs, notebook, etc.
> AbsSys Abund

- docs/examples/RelAbund.ipynb
- docs/index.rst
- docs/relabund.rst
- linetools/abund/relabund.py
- linetools/abund/solar.py
- linetools/abund/tests/test_relabnd.py
- linetools/isgm/utils.py
Class for handling relative abundances.  
Mainly for an AbsSystem.  And maybe 
mainly for DLAs
Tests and doc strings too
Will add a short Notebook and 
an .rst file before merging.
> Relative Abundances Class

- linetools/spectra/tests/test_xspectrum_utils.py
- linetools/spectra/xspectrum1d.py
- setup.py
Bug fix for rebinning spectra with units on Flux
> Rebin Flux

- docs/scripts.rst
- linetools/abund/ions.py
- linetools/scripts/lt_line.py
- linetools/scripts/tests/test_scripts.py
- setup.py
New script for print the data for a spectral line (or lines)
Includes test and docs
> Line script

- docs/scripts.rst
- linetools/scripts/lt_line.py
- linetools/scripts/tests/test_scripts.py
Adds an option to show redshift lines in lt_line
As per @astronomeara request
@astronomeaera is pleased
> Add z to lt_line

- docs/install.rst
As titled.
@nhmc is this automatically updated on readthedocs?
> Remove specutilts from Install docs

- docs/install.rst
- docs/scripts.rst
- docs/xspecgui.rst
- linetools/scripts/lt_continuumfit.py
- linetools/scripts/lt_xspec.py
> Conti docs

- linetools/analysis/plots.py
- linetools/isgm/abscomponent.py
- linetools/isgm/abssystem.py
- linetools/isgm/tests/test_init_abscomp.py
- linetools/isgm/tests/test_init_abssys.py
- linetools/isgm/utils.py
- linetools/spectralline.py
- linetools/utils.py
Mainly a new method to convert a list of components (e.g. from
igmguesses) into a list of AbsSystem's.
Includes a test
No new docs other than inline
> Component and system fiddling

- linetools/guis/spec_widgets.py
> xspec: plot filename of spectrum (if any).

- linetools/isgm/abssystem.py
> minor tweaks for speed up in abssystem

- .travis.yml
- CHANGES.rst
- docs/install.rst
- docs/xspectrum1d.rst
- linetools/analysis/plots.py
- linetools/analysis/tests/test_continuum.py
- linetools/spectra/io.py
- linetools/spectra/tests/test_read_fits_spec.py
- linetools/spectra/tests/test_xspec_init.py
- linetools/spectra/tests/test_xspectrum_utils.py
- linetools/spectra/utils.py
- linetools/spectra/xspectrum1d.py
This started as a new method to stich spectra together.
It grew into a significant refactoring due to the masked arrays.
Not sure I am regretting the change, but this was a bit painful..
Docs for XSpectrum1D need updating.  Didn't have the endurance
to do that.
New and many revised tests
> Stitch and much more

- linetools/spectra/tests/test_xspectrum_utils.py
- linetools/spectra/xspectrum1d.py
Fixes a bug in the copy method
Adds a test that would have caught it (I think).
> XSpec Copy fix

- docs/scripts.rst
- linetools/scripts/lt_absline.py
- linetools/scripts/lt_line.py
- linetools/scripts/tests/test_scripts.py
Some new functionality for lt_line and lt_absline
> Script improvements

- linetools/spectra/tests/test_xspec_init.py
- linetools/spectra/xspectrum1d.py
As stated. I still do not like much representing the flux, sigma attributed using MaskedArray.compressed()...
> fit continuum: fixed to handle the masked arrays.

- linetools/guis/spec_widgets.py
- linetools/guis/xspecgui.py
- linetools/scripts/lt_xspec.py
- linetools/spectra/tests/test_xspectrum_utils.py
- linetools/spectra/xspectrum1d.py
air to vac method in xspectrum1D
test
added option to lt_xspec
> Air to vac

- linetools/analysis/abskin.py
- linetools/lists/linelist.py
One to avoid redoing the extra_columns
One related to kinematics
> Two small fixes

- linetools/lists/linelist.py
> linelist: adding option to redo extra columns at the .__init__ level.

- linetools/guis/spec_widgets.py
- linetools/guis/xspecgui.py
- linetools/scripts/lt_xspec.py
Add 'q' as the key to quit lt_xspec
Addresses Issue#243
Also fixes a dumb bug
Tested by JXP
> q is for Quit

- linetools/spectralline.py
- linetools/tests/test_init_absline.py
Small edits for AbsLine I/O
Test modified too
no docs
> I/O for AbsLine

- linetools/abund/tests/test_elements.py
- linetools/abund/tests/test_ions.py
- linetools/abund/tests/test_solar.py
- linetools/analysis/interactive_plot.py
- linetools/analysis/tests/test_interactive_plot.py
- linetools/analysis/tests/test_voigt.py
- linetools/guis/tests/test_guis.py
- linetools/guis/utils.py
- linetools/scripts/tests/test_scripts.py
- linetools/spectra/tests/test_lsf_init.py
- linetools/spectra/tests/test_lsf_use.py
- linetools/spectra/tests/test_read_fits_spec.py
- linetools/tests/test_line_utils.py
> Test coverage

- linetools/guis/tests/test_guis.py
- linetools/spectra/tests/test_lsf_use.py
> increasing coverage

- linetools/analysis/plots.py
- linetools/analysis/tests/test_absline.py
- linetools/analysis/tests/test_plots.py
Testing test coverage for plots... with `show=True` does not work of course... `show=False` it is.
> more coverage: analysis plot

- linetools/spectra/xspectrum1d.py
Show continuum in xspec.plot()
Fixes a logic bug
> Show continuum

- linetools/guis/line_widgets.py
New option in select_line_widget adding redshift of line if such keyword (i.e. `'redshift'`) is present in the input table. Useful for IGMGuesses and potentially other GUIs too.
> Line widget

- linetools/spectra/tests/test_xspectrum_utils.py
- linetools/spectra/xspectrum1d.py
Handles NANs in flux array
Test too
> NANs in xspectrum1d.rebin

- linetools/guis/line_widgets.py
> Gui line fix

- docs/xspecgui.rst
- docs/xspectrum1d.rst
- linetools/spectra/tests/test_xspectrum_utils.py
- linetools/spectra/xspectrum1d.py
Introduce an inverse variance smoothing method.
Port of ivarsmooth from IDL
Includes test and sparse doc.
Addresses Issue #285
> ivarsmooth method

- linetools/spectra/xspectrum1d.py
Changes ordering of error and wavelength.
No new tests or docs
> Push error writing 

- docs/scripts.rst
- linetools/scripts/lt_radec.py
- linetools/scripts/tests/test_scripts.py
- linetools/scripts/utils.py
Enables another radec input for scripts.
Pushes code to utils
Added doc and test
> Another radec input for scripts

- .travis.yml
- linetools/spectra/xspectrum1d.py
- linetools/utils.py
Moves it from XSpectrum1D to linetools.utils
> Move rel_vel method

- docs/xspectrum1d.rst
> Tiny doc edit

- docs/xspectrum1d.rst
- linetools/spectra/tests/test_xspec_attrib.py
- linetools/spectra/tests/test_xspec_init.py
- linetools/spectra/tests/test_xspec_methods.py
- linetools/spectra/tests/test_xspec_utils.py
- linetools/spectra/utils.py
- linetools/spectra/xspectrum1d.py
Additional edits to xspectrum1d.
Tests, docs
> Masking and more

- docs/xspectrum1d.rst
Fixed by removing most of the tests in the doc string.
Not sure why these were ever passing..
> Fix doc test

- docs/xspectrum1d.rst
- linetools/spectra/tests/test_xspec_attrib.py
- linetools/spectra/tests/test_xspec_io.py
- linetools/spectra/tests/test_xspec_methods.py
- linetools/spectra/tests/test_xspec_utils.py
- linetools/spectra/xspectrum1d.py
Adds a method to calculate the average local signal-to-noise, with tests.
> Xspectrum1d local s2n

- linetools/isgm/abssystem.py
- linetools/tests/test_utils.py
- linetools/utils.py
Adds a new method to writing jSON files which is easier to read.
Preserves the old methods as default
Adds a test
> Easier to read JSON file

- CHANGES.rst
- linetools/spectra/xspectrum1d.py
- fixes bug in get_local_s2n
- adds some changes to CHANGES.rst
> Miscelaneous

- linetools/scripts/lt_radec.py
> lt_radec: added some extra representations

- docs/abssightline.rst
- docs/examples/AbsSightline.ipynb
- docs/index.rst
- linetools/isgm/abscomponent.py
- linetools/isgm/abssightline.py
- linetools/isgm/abssystem.py
- linetools/isgm/tests/test_init_abssightline.py
- linetools/isgm/tests/test_init_abssys.py
- linetools/isgm/tests/test_use_abssightline.py
- linetools/isgm/tests/utils.py
- linetools/isgm/utils.py
- linetools/tests/test_utils.py
- linetools/utils.py
Creates AbsSightline class.
It is mainly a simple object to hold a set of 
AbsComponent objects along a sightline on the sky.
A few other updates snuck in as well.
Tests and docs.
> AbsSightline

- linetools/analysis/absline.py
- linetools/analysis/tests/test_absline.py
- linetools/lists/linelist.py
- linetools/spectralline.py
- linetools/tests/test_absline_anly.py
- Added function to calculate tau0 at line center.
- Added function to estimate equivalent width from logN and b for a given transition.
- Both with tests
Please review but do not merge yet; I intend to add a couple of extra ones that build from these.
> Analysis abslines

- docs/abscomp.rst
- docs/examples/AbsComponent_examples.ipynb
- docs/examples/AbsLine_examples.ipynb
- docs/specline.rst
- linetools/analysis/linelimits.py
- linetools/analysis/plots.py
- linetools/analysis/tests/test_linelimits.py
- linetools/analysis/tests/test_voigt.py
- linetools/analysis/voigt.py
- linetools/isgm/abscomponent.py
- linetools/isgm/tests/test_init_abscomp.py
- linetools/spectralline.py
- linetools/tests/test_absline_anly.py
- linetools/tests/test_init_absline.py
Attemps to expunge usage of attrib['z'] in SpectralLine
Wound up refactoring LineLimits too, a bit.
Lots of edtis to docs and tests.
Addresses Issue #307
> Refactor z in SpectralLine

- docs/abscomp.rst
- linetools/analysis/tests/test_voigt.py
- linetools/analysis/voigt.py
- linetools/spectralline.py
- linetools/tests/test_init_absline.py
> Voigt: Voigt model from component list

- docs/examples/Scripts.ipynb
- linetools/isgm/tests/test_use_abscomp.py
- linetools/isgm/utils.py
Addresses the parameter inputs for joebvp that are extracted through IGMguesses
> joebvpParFix

- linetools/analysis/linelimits.py
- linetools/spectra/tests/test_xspec_utils.py
- linetools/spectra/xspectrum1d.py
- linetools/tests/test_utils.py
- linetools/utils.py
Idea is to refactor functions related to passing from dv to dz and vice-versa. This PR should address issue #330 . 
Please review this initial commit without merging before starting the major refactor.
> Refactor dvdz

- linetools/lists/linelist.py
- linetools/lists/tests/test_use_linelist.py
- linetools/utils.py
Addresses Issue #317 
Working on this, I came to the conclusion that we should revisit the way things are done internally within LineList to treat atomic transitions versus molecular transitions. We may need redefine better namings for columns in self._data. Probably best to leave for a separate issue.
> Llist h2: implement basic rel_strength and all_transition() method

- docs/abscomp.rst
- linetools/analysis/absline.py
- linetools/analysis/tests/test_absline.py
- linetools/analysis/voigt.py
- linetools/isgm/abscomponent.py
- linetools/isgm/tests/test_use_abscomp.py
- linetools/isgm/utils.py
- linetools/spectralline.py
- linetools/tests/test_absline_anly.py
- complist_from_table() 
- get_components_at_z()
These two simple general methods added, with tests.
> Abscomponents: complist_from_table and other

- linetools/lists/linelist.py
- linetools/lists/parse.py
As titled.  A few QTable manoeuvers for line lists.
No new tests or docs.
> Small fixes to satisfy astropy v1.3

- linetools/analysis/plots.py
- linetools/isgm/abscomponent.py
Added options to return matplotlib Figure instance of stackplot and apply tight_layout
> Features for analysis.plots.stack_plot()

- linetools/guis/spec_widgets.py
Also adds a small QtWrapper for ExamineSpec
so that it may be launched by other GUI's (e.g. igmguesses).
No new docs or tests.
> Add EW measurement in xspec

- linetools/guis/spec_widgets.py
- linetools/guis/xabssysgui.py
- linetools/isgm/abscomponent.py
- linetools/isgm/abssystem.py
- linetools/isgm/tests/test_init_abscomp.py
- linetools/isgm/utils.py
- linetools/scripts/lt_xabssys.py
- linetools/spectra/io.py
- linetools/spectra/utils.py
Several small changes including a bug fix or two,
mainly related to AbsSystem objects.
Also modified the splice algorithm for spectra.
Tests updated.
No new docs.
> AbsSystem Miscellany

- linetools/spectra/io.py
> Added  "Angstroms" as potential wavelength unit (STIS format).

- linetools/spectra/io.py
Fixing the header (again).  
Searches for the trailing } this time.
> Fixing the header (again)

- linetools/guis/spec_widgets.py
Added a new widget to the spec_widgets module.
It is primarily to support line-fitting guis which will locate
in pyigm.
No docs or tests
> AbsSys widget

- linetools/guis/spec_widgets.py
Good old attrib issue.
No docs or tests
> Fix DLA option in XSpec

- linetools/scripts/lt_xspec.py
- linetools/spectralline.py
Modified the script doc
Minor edit to _repr_ for AbsLine
no tests
> Small edits for lt_xspec

- docs/absline.rst
- docs/abssys.rst
- docs/specline.rst
- linetools/analysis/plots.py
- linetools/isgm/abssystem.py
- linetools/isgm/tests/test_use_abssys.py
Require do_analysis=1 when analyzing EWs in AbsSystem
Also a bug fix, new docs and tests.
> EW using do_analysis

- .travis.yml
- linetools/guis/line_widgets.py
- linetools/guis/simple_widgets.py
- linetools/guis/spec_widgets.py
- linetools/guis/utils.py
- linetools/guis/xabssysgui.py
- linetools/guis/xspecgui.py
- linetools/scripts/lt_xspec.py
- setup.py
As titled, this begins the refactoring to PyQt5 for GUIs.
I've successfully run lt_xspec with Python 3.6 but can't
guarantee that all functionality is ok.  But I am somewhat optimistic.
I cannot get things to pass Travis but cannot see how this is my fault.
No new docs or tests.
> Refactor for PyQt5

- linetools/guis/simple_widgets.py
- linetools/guis/spec_widgets.py
> PyQT5 Refactoring continues

- linetools/guis/line_widgets.py
A missing piece for PyQt4->PyQt5
> PyQt4->PyQt5 in line_widgets.py

- linetools/abund/relabund.py
- linetools/guis/tests/test_guis.py
- linetools/isgm/abscomponent.py
- linetools/isgm/utils.py
- linetools/scripts/lt_line.py
- linetools/spectra/io.py
- linetools/spectra/utils.py
- linetools/spectra/xspectrum1d.py
- setup.cfg
Plotting and I/O
No new tests or docs
> Minor edits related to XSpectrum1D

- linetools/scripts/lt_xabssys.py
- linetools/scripts/lt_xspec.py
> Refactoring for PyQt5 with xabssysgui

- linetools/guis/line_widgets.py
- linetools/guis/spec_widgets.py
Fixes some kind of quantity bug with matplotlib.
I think.
i.e. Issue #375
> Bug fix in lt_xspec

- linetools/isgm/abscomponent.py
Almost there.  Am sure I'll deprecate it
altogether before long.
> Toward deprecating ion_name and name_ion

- linetools/lists/linelist.py
- linetools/lists/tests/test_linelist_utils.py
- linetools/lists/utils.py
Stripped these out to a new utils.py module.
Added a test.
> Refactor table_to_dict in linelists

- linetools/guis/spec_widgets.py
> Simple GUI edit

- linetools/analysis/interactive_plot.py
As titled.  Fixes bug that was resulting
in continuum fitting.
> Python3 fix for raw_input

- linetools/guis/xspecgui.py
> Lingering QTable refactor

- docs/install.rst
- docs/scripts.rst
- linetools/guis/line_widgets.py
- linetools/guis/spec_widgets.py
- linetools/guis/xspecgui.py
- linetools/scripts/lt_xspec.py
Updates the install notes for PyQt5
Also allows user to rescale the GUI.  
Most useful for small screens with very high pixel resolution (e.g. my Dell XPS).
> Update PyQt5 doc + GUI scale parameter

- docs/scripts.rst
- linetools/abund/solar.py
- linetools/scripts/lt_solabnd.py
- linetools/scripts/tests/test_scripts.py
- setup.py
Simple script to show a solar abundance value.
Docs and test too.
> Solar Abundance script

- linetools/tests/test_utils.py
- linetools/utils.py
Added `is_local_minima_maxima()` and `is_local_minima_maxima()` utilities for 1-d array analysis. Test added too.
> Utils: Local minima/maxima for 1-d array values

- linetools/isgm/abscomponent.py
> definable velocity limits for abscomponent.stack_plot()

- linetools/isgm/abssystem.py
- linetools/isgm/tests/test_use_abssys.py
- linetools/spectralline.py
Minor updates:
- I/O
- nsig for measure_ew
No new tests or docs
> Updates to AbsSystem

- linetools/analysis/interactive_plot.py
- linetools/spectra/xspectrum1d.py
toggle initial continuum display in GUI
make optional number of pixels used when guessing knot location by median flux
> ContinuumFitModifications

- linetools/lists/linelist.py
- linetools/lists/mk_sets.py
- linetools/lists/tests/test_init_linelist.py
Fixes a bug or two.
Added a test
Note that the EUV line list is no longer cached.
> Edits to make Xray lines actually accessible

- linetools/spectra/utils.py
Small fix to avoid units.
Am worried there is still a units bug 
in the var array but I don't think it will
cause trouble.
> Remove units in new_sig

- linetools/spectra/io.py
- linetools/spectra/tests/test_xspec_init.py
- linetools/spectra/tests/test_xspec_methods.py
- linetools/spectra/tests/test_xspec_utils.py
- linetools/spectra/utils.py
- linetools/spectra/xspectrum1d.py
Mainly propagates masking choice into collate.
No new docs or tests
> Turn off masking

- linetools/analysis/linelimits.py
- linetools/spectralline.py
And turns one on when instantiating an AbsLine
without an input redshift.
No new docs or tests
> Turning off z warning in LineLimit

- linetools/guis/spec_widgets.py
- linetools/guis/xspecgui.py
As titled.
No new docs or tests.
> Small GUI fixes for pyqt5 and Python3

- docs/examples/AbsLine_examples.ipynb
- linetools/isgm/abssightline.py
- linetools/isgm/tests/test_init_abssightline.py
- linetools/isgm/tests/utils.py
> AbsSightline from_systems()

- CHANGES.rst
- setup.py
> update changes for v0.3

- linetools/isgm/abssightline.py
Extremely minor **kwargs addition to AbsSightline.from_systems()
> Abssightline fix

- linetools/spectra/lsf.py
Added `wv0` information for error in LSF interpolation.
> Adds info in error message for LSF interpolations

- linetools/lists/parse.py
File placed after "def read_galabs():", I wasn't sure where to put it. Let me know if this is okay and if I need to modify anything.
> Update parse.py to include "read_cashman17()"

- linetools/spectra/tests/test_utils.py
- linetools/spectra/utils.py
> Added utility function to get HST/COS Life-time position and test.

- linetools/isgm/abscomponent.py
- linetools/isgm/io.py
Fussing with a few tests to address the last PR. 
Should have caught these before merging, but alas.
> Attrib fixes

- linetools/isgm/abscomponent.py
- linetools/isgm/tests/test_init_abscomp.py
- linetools/lists/linelist.py
Dealing a bit better with zero values.
I think.
Tests updated.  Passing on my workstation
but not Travis (which seems a bit broken).
> More fussing with generating AbsComponent from AbsLines

- linetools/isgm/abssystem.py
- linetools/spectra/utils.py
- linetools/spectra/xspectrum1d.py
Add keyword coord to AbsSystem.from_dict() method
And a change to splicing the XSpectrum1D object.
> Coord to AbsSystem

- linetools/isgm/tests/test_use_abscomp.py
Added test for copy() in AbsComponent object.
> test for AbsComponent.copy()

- ah_bootstrap.py
- setup.py
removes an (old) bad line in setup.py
also updates ah_boostrap.py
Probably should have done so years ago  ;)
> Update astropy helpers

- linetools/analysis/voigt.py
- linetools/spectra/tests/test_xspec_utils.py
- linetools/spectra/utils.py
- linetools/spectra/xspectrum1d.py
Extrapolating on error array was a bad idea..
Fixed and tests updated
> Hot fix on the rebin method 

- linetools/guis/xspecgui.py
- linetools/isgm/abscomponent.py
- linetools/isgm/abssightline.py
- linetools/isgm/abssystem.py
- linetools/isgm/tests/test_use_abscomp.py
- linetools/isgm/tests/test_use_abssightline.py
- linetools/isgm/tests/utils.py
- linetools/isgm/utils.py
Bits and pieces throughout the modules in linetools.isgm
Mainly for writing and loading those objects.
Also, a few updates related to limits in components.
A new test.  
No new docs aside from doc strings.
> AbsLine survey advances

- linetools/guis/spec_widgets.py
> GUI add on

- linetools/scripts/lt_radec.py
- linetools/tests/test_utils.py
- linetools/utils.py
> Add galactic coords option to lt_radec

- linetools/_astropy_init.py
This is an automated update made by the astropy package-template ``batchpr``
tool :robot: - feel free to close if it doesn't look good!
You can report issues to @bsipocz.
> Package-template update: _astropy_init.py

- linetools/isgm/tests/test_use_abscomp.py
As stated, address some failed tests dealing with AbsComponent.
> Fix test_repr_joebvp Travis errors

- linetools/abund/ions.py
> name_to_ion fix infinite recursive

- linetools/spectra/lsf.py
- linetools/spectra/tests/test_lsf_init.py
- linetools/spectra/tests/test_lsf_use.py
- linetools/spectra/utils.py
Bug fixes/feature additions for stacking spectra.  Also, Gaussian line spread functions are now supported within LSF class with appropriate method handling.  New tests for LSF init and usage.
> Stacking and Gaussian LSFs

- linetools/analysis/plots.py
- linetools/analysis/zlimits.py
Correcting errors occurring when passing component lists to stack_plot and in extracting json from CGMSurvey.
> Limits and stack_plot fix

- .travis.yml
- docs/install.rst
- linetools/spectra/tests/test_xspec_methods.py
- linetools/spectra/tests/test_xspec_utils.py
Updates Travis and the requirements for advances elsewhere.
I've had to turn off coverage as that now fails with the 
current astropy helpers.   Am hoping they will update it
to work before long.
> Travis fixes and updates

- linetools/spectra/tests/test_xspec_utils.py
- linetools/spectra/utils.py
Fixed a bug in rebin_to_rest and refactored rebin() to speed up by >300x
> Rebin fixes

- .travis.yml
- CHANGES.rst
- docs/install.rst
- linetools/analysis/interactive_plot.py
- linetools/analysis/plots.py
- linetools/guis/line_widgets.py
- linetools/guis/simple_widgets.py
- linetools/guis/spec_widgets.py
- linetools/guis/tests/test_guis.py
- linetools/guis/xabssysgui.py
- linetools/guis/xspecgui.py
- linetools/isgm/abscomponent.py
- linetools/scripts/lt_xabssys.py
- linetools/scripts/lt_xspec.py
- linetools/spectra/xspectrum1d.py
PySide2 has a more permissive license (LGPL 3) than PyQt5 (GPL 3), and practically the same public API.
> Refactor PyQt5 -> PySide2

- .travis.yml
- CHANGES.rst
- docs/install.rst
- linetools/guis/line_widgets.py
- linetools/guis/simple_widgets.py
- linetools/guis/spec_widgets.py
- linetools/guis/tests/test_guis.py
- linetools/guis/xabssysgui.py
- linetools/guis/xspecgui.py
- linetools/scripts/lt_xabssys.py
- linetools/scripts/lt_xspec.py
- linetools/spectra/io.py
- linetools/spectra/xspectrum1d.py
what it says on the tin
Current test status on macos
``====== 3 failed, 232 passed, 1 skipped, 228 warnings in 166.17s (0:02:46) ======``
The failing tests are in `linetools/spectra/tests/test_xspec_io.py` and are all reporting `E   OSError: Unable to create file (unable to lock file, errno = 35, error message = 'Resource temporarily unavailable')` when writing to hdf5, might just be a problem with my machine.
> refactor pyside2 -> qtpy

- linetools/guis/line_widgets.py
- linetools/lists/linelist.py
- linetools/lists/parse.py
- linetools/scripts/lt_xspec.py
As titled.
I imagine there will be more to come..
> Updates for pyqt6 (and another fix or two)

- .github/workflows/ci_tests.yml
- pyproject.toml
- setup.py
> BLD: cleanup unused build-time dependencies

- linetools/abund/solar.py
- linetools/lists/parse.py
This minor PR suppresses unnecessary printing to the screen when performing basic operations.
> Verbosity fix
